### ISSUE TITLE
Wazuh-Sigma rules Sigwah 

### ISSUE THREAD

**Issue by AakashR2208** [branchnetconsulting/wazuh-tools#6]
Hi Kevin, 

Thanks for sharing these scripts as they are very useful. 
I am working on integrating the Sigma rules into the wazuh rule set.  I am using the import sigwah script to do this. 

But after I ran the script and restarted the cluster, the manager could not restart and gave me a configuration error: 
```
2020/07/21 17:47:39 ossec-analysisd: ERROR: Invalid configuration. 'group' is no                                                                                 t a valid element.
2020/07/21 17:47:39 ossec-analysisd: CRITICAL: (1220): Error loading the rules:                                                                                  'etc/rules/sigwah.xml'.
ossec-analysisd: Configuration error. Exiting
```
I checked the sigwah.xml file and the syntax and formatting seems to be good. 

Could you please tell me how to resolve this issue or do something differently. 

Thanks
Aakash

**Comment by branchnetconsulting** [comment]
With a recent PR merged, I believe this is now resolved.

Kevin
