### ISSUE TITLE
show-wazuh-rule missing output

### ISSUE THREAD

**Issue by geoffbernard-bw** [branchnetconsulting/wazuh-tools#60]
If I run the script as posted, this is the output:

Processing /var/ossec/ruleset/rules/0020-syslog_rules.xml
 
I'm not seeing the actual rule displayed. I found if I changed the grep line from this:
grep  -Pzo "^.*<rule id=\"$ID\" .*(.|\n)*?</rule>" $F -h

to this:
grep  -Pzo "<rule id=\"$ID\" .*(.|\n)*?</rule>" $F -h

I get the following output:
Processing /var/ossec/ruleset/rules/0020-syslog_rules.xml
<rule id="5100" level="0" noalert="1">
    <program_name>^kernel</program_name>
    <description>Pre-match rule for kernel messages.</description>
  </rule>

I'm running on Ubuntu 20.04 - I also was able to run the modified line on EC2 Linux and it worked there as well. I'm by no means a Linux or regex expert but for some reason, the ^.* at the start of the grep line caused the output to be suppressed.

Do you have any thoughts?

**Comment by branchnetconsulting** [comment]
Thanks for noting this.  I have adjusted the script.
